//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.15 at 01:36:40 PM CST 
//


package com.ibm.ws.jpa.diagnostics.tools.appscanner.report.pascanresult.v10;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PersistentArchiveScanResultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersistentArchiveScanResultType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="persistence" type="{PersistentArchiveScanResult_1.0}PersistenceParseResultType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement
@XmlType(name = "PersistentArchiveScanResultType", propOrder = {
    "persistence"
})
public class PersistentArchiveScanResultType {

    @XmlElement(required = true)
    protected PersistenceParseResultType persistence;

    /**
     * Gets the value of the persistence property.
     * 
     * @return
     *     possible object is
     *     {@link PersistenceParseResultType }
     *     
     */
    public PersistenceParseResultType getPersistence() {
        return persistence;
    }

    /**
     * Sets the value of the persistence property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersistenceParseResultType }
     *     
     */
    public void setPersistence(PersistenceParseResultType value) {
        this.persistence = value;
    }

}
