//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.08 at 04:07:33 PM CST 
//


package com.ibm.ws.jpa.diagnostics.orm.ano.jaxb.classinfo10;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ClassInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClassInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="modifiers" type="{ClassInfo_1.0}ModifiersType" minOccurs="0"/>
 *         &lt;element name="annotations" type="{ClassInfo_1.0}AnnotationsType" minOccurs="0"/>
 *         &lt;element name="interfaces" type="{ClassInfo_1.0}InterfacesType" minOccurs="0"/>
 *         &lt;element name="fields" type="{ClassInfo_1.0}FieldsType" minOccurs="0"/>
 *         &lt;element name="methods" type="{ClassInfo_1.0}MethodsType" minOccurs="0"/>
 *         &lt;element name="innerclasses" type="{ClassInfo_1.0}InnerClassesType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="className" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="superclassName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="packageName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="isAnonymous" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isEnum" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isInterface" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isSynthetic" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClassInfoType", propOrder = {
    "modifiers",
    "annotations",
    "interfaces",
    "fields",
    "methods",
    "innerclasses"
})
@XmlRootElement
public class ClassInfoType {

    protected ModifiersType modifiers;
    protected AnnotationsType annotations;
    protected InterfacesType interfaces;
    protected FieldsType fields;
    protected MethodsType methods;
    protected InnerClassesType innerclasses;
    @XmlAttribute(name = "className", required = true)
    protected String className;
    @XmlAttribute(name = "superclassName", required = true)
    protected String superclassName;
    @XmlAttribute(name = "packageName", required = true)
    protected String packageName;
    @XmlAttribute(name = "isAnonymous")
    protected Boolean isAnonymous;
    @XmlAttribute(name = "isEnum")
    protected Boolean isEnum;
    @XmlAttribute(name = "isInterface")
    protected Boolean isInterface;
    @XmlAttribute(name = "isSynthetic")
    protected Boolean isSynthetic;
    @XmlAttribute(name = "version", required = true)
    protected int version;

    /**
     * Gets the value of the modifiers property.
     * 
     * @return
     *     possible object is
     *     {@link ModifiersType }
     *     
     */
    public ModifiersType getModifiers() {
        return modifiers;
    }

    /**
     * Sets the value of the modifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModifiersType }
     *     
     */
    public void setModifiers(ModifiersType value) {
        this.modifiers = value;
    }

    /**
     * Gets the value of the annotations property.
     * 
     * @return
     *     possible object is
     *     {@link AnnotationsType }
     *     
     */
    public AnnotationsType getAnnotations() {
        return annotations;
    }

    /**
     * Sets the value of the annotations property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnnotationsType }
     *     
     */
    public void setAnnotations(AnnotationsType value) {
        this.annotations = value;
    }

    /**
     * Gets the value of the interfaces property.
     * 
     * @return
     *     possible object is
     *     {@link InterfacesType }
     *     
     */
    public InterfacesType getInterfaces() {
        return interfaces;
    }

    /**
     * Sets the value of the interfaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link InterfacesType }
     *     
     */
    public void setInterfaces(InterfacesType value) {
        this.interfaces = value;
    }

    /**
     * Gets the value of the fields property.
     * 
     * @return
     *     possible object is
     *     {@link FieldsType }
     *     
     */
    public FieldsType getFields() {
        return fields;
    }

    /**
     * Sets the value of the fields property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldsType }
     *     
     */
    public void setFields(FieldsType value) {
        this.fields = value;
    }

    /**
     * Gets the value of the methods property.
     * 
     * @return
     *     possible object is
     *     {@link MethodsType }
     *     
     */
    public MethodsType getMethods() {
        return methods;
    }

    /**
     * Sets the value of the methods property.
     * 
     * @param value
     *     allowed object is
     *     {@link MethodsType }
     *     
     */
    public void setMethods(MethodsType value) {
        this.methods = value;
    }

    /**
     * Gets the value of the innerclasses property.
     * 
     * @return
     *     possible object is
     *     {@link InnerClassesType }
     *     
     */
    public InnerClassesType getInnerclasses() {
        return innerclasses;
    }

    /**
     * Sets the value of the innerclasses property.
     * 
     * @param value
     *     allowed object is
     *     {@link InnerClassesType }
     *     
     */
    public void setInnerclasses(InnerClassesType value) {
        this.innerclasses = value;
    }

    /**
     * Gets the value of the className property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassName() {
        return className;
    }

    /**
     * Sets the value of the className property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassName(String value) {
        this.className = value;
    }

    /**
     * Gets the value of the superclassName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuperclassName() {
        return superclassName;
    }

    /**
     * Sets the value of the superclassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuperclassName(String value) {
        this.superclassName = value;
    }

    /**
     * Gets the value of the packageName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPackageName() {
        return packageName;
    }

    /**
     * Sets the value of the packageName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPackageName(String value) {
        this.packageName = value;
    }

    /**
     * Gets the value of the isAnonymous property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsAnonymous() {
        return isAnonymous;
    }

    /**
     * Sets the value of the isAnonymous property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsAnonymous(Boolean value) {
        this.isAnonymous = value;
    }

    /**
     * Gets the value of the isEnum property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsEnum() {
        return isEnum;
    }

    /**
     * Sets the value of the isEnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsEnum(Boolean value) {
        this.isEnum = value;
    }

    /**
     * Gets the value of the isInterface property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsInterface() {
        return isInterface;
    }

    /**
     * Sets the value of the isInterface property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsInterface(Boolean value) {
        this.isInterface = value;
    }

    /**
     * Gets the value of the isSynthetic property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsSynthetic() {
        return isSynthetic;
    }

    /**
     * Sets the value of the isSynthetic property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsSynthetic(Boolean value) {
        this.isSynthetic = value;
    }

    /**
     * Gets the value of the version property.
     * 
     */
    public int getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     */
    public void setVersion(int value) {
        this.version = value;
    }

}
