//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.08 at 04:07:33 PM CST 
//


package com.ibm.ws.jpa.diagnostics.orm.ano.jaxb.classinfo10;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExceptionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExceptionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="exceptionType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="superclassType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="isRuntimeException" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExceptionType")
public class ExceptionType {

    @XmlAttribute(name = "exceptionType")
    protected String exceptionType;
    @XmlAttribute(name = "superclassType")
    protected String superclassType;
    @XmlAttribute(name = "isRuntimeException")
    protected Boolean isRuntimeException;

    /**
     * Gets the value of the exceptionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExceptionType() {
        return exceptionType;
    }

    /**
     * Sets the value of the exceptionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExceptionType(String value) {
        this.exceptionType = value;
    }

    /**
     * Gets the value of the superclassType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuperclassType() {
        return superclassType;
    }

    /**
     * Sets the value of the superclassType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuperclassType(String value) {
        this.superclassType = value;
    }

    /**
     * Gets the value of the isRuntimeException property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsRuntimeException() {
        return isRuntimeException;
    }

    /**
     * Sets the value of the isRuntimeException property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsRuntimeException(Boolean value) {
        this.isRuntimeException = value;
    }

}
