//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.08 at 04:07:33 PM CST 
//


package com.ibm.ws.jpa.diagnostics.orm.ano.jaxb.classinfo10;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ModifierType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ModifierType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ABSTRACT"/>
 *     &lt;enumeration value="FINAL"/>
 *     &lt;enumeration value="INTERFACE"/>
 *     &lt;enumeration value="NATIVE"/>
 *     &lt;enumeration value="PRIVATE"/>
 *     &lt;enumeration value="PROTECTED"/>
 *     &lt;enumeration value="PUBLIC"/>
 *     &lt;enumeration value="STATIC"/>
 *     &lt;enumeration value="STRICT"/>
 *     &lt;enumeration value="SYNCHRONIZED"/>
 *     &lt;enumeration value="TRANSIENT"/>
 *     &lt;enumeration value="VOLATILE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ModifierType")
@XmlEnum
public enum ModifierType {

    ABSTRACT,
    FINAL,
    INTERFACE,
    NATIVE,
    PRIVATE,
    PROTECTED,
    PUBLIC,
    STATIC,
    STRICT,
    SYNCHRONIZED,
    TRANSIENT,
    VOLATILE;

    public String value() {
        return name();
    }

    public static ModifierType fromValue(String v) {
        return valueOf(v);
    }

}
