/*******************************************************************************
 * Copyright (c) 2011, 2017 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.28 at 03:35:02 PM CDT 
//


package com.ibm.ws.jpa.diagnostics.orm.ano.jaxb.classinfo10;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ibm.ws.jpa.diagnostics.orm.ano.jaxb.classinfo10 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ClassInformation_QNAME = new QName("ClassInfo_1.0", "ClassInformation");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ibm.ws.jpa.diagnostics.orm.ano.jaxb.classinfo10
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ClassInformationType }
     * 
     */
    public ClassInformationType createClassInformationType() {
        return new ClassInformationType();
    }

    /**
     * Create an instance of {@link ExceptionType }
     * 
     */
    public ExceptionType createExceptionType() {
        return new ExceptionType();
    }

    /**
     * Create an instance of {@link InnerClassesType }
     * 
     */
    public InnerClassesType createInnerClassesType() {
        return new InnerClassesType();
    }

    /**
     * Create an instance of {@link ParameterType }
     * 
     */
    public ParameterType createParameterType() {
        return new ParameterType();
    }

    /**
     * Create an instance of {@link AnnotationElementValueType }
     * 
     */
    public AnnotationElementValueType createAnnotationElementValueType() {
        return new AnnotationElementValueType();
    }

    /**
     * Create an instance of {@link ModifiersType }
     * 
     */
    public ModifiersType createModifiersType() {
        return new ModifiersType();
    }

    /**
     * Create an instance of {@link AnnotationInfoType }
     * 
     */
    public AnnotationInfoType createAnnotationInfoType() {
        return new AnnotationInfoType();
    }

    /**
     * Create an instance of {@link FieldsType }
     * 
     */
    public FieldsType createFieldsType() {
        return new FieldsType();
    }

    /**
     * Create an instance of {@link AnnotationsType }
     * 
     */
    public AnnotationsType createAnnotationsType() {
        return new AnnotationsType();
    }

    /**
     * Create an instance of {@link ClassInfoType }
     * 
     */
    public ClassInfoType createClassInfoType() {
        return new ClassInfoType();
    }

    /**
     * Create an instance of {@link FieldInfoType }
     * 
     */
    public FieldInfoType createFieldInfoType() {
        return new FieldInfoType();
    }

    /**
     * Create an instance of {@link AnnotationElementType }
     * 
     */
    public AnnotationElementType createAnnotationElementType() {
        return new AnnotationElementType();
    }

    /**
     * Create an instance of {@link MethodsType }
     * 
     */
    public MethodsType createMethodsType() {
        return new MethodsType();
    }

    /**
     * Create an instance of {@link InterfacesType }
     * 
     */
    public InterfacesType createInterfacesType() {
        return new InterfacesType();
    }

    /**
     * Create an instance of {@link ExceptionsType }
     * 
     */
    public ExceptionsType createExceptionsType() {
        return new ExceptionsType();
    }

    /**
     * Create an instance of {@link ParametersType }
     * 
     */
    public ParametersType createParametersType() {
        return new ParametersType();
    }

    /**
     * Create an instance of {@link MethodInfoType }
     * 
     */
    public MethodInfoType createMethodInfoType() {
        return new MethodInfoType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClassInformationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ClassInfo_1.0", name = "ClassInformation")
    public JAXBElement<ClassInformationType> createClassInformation(ClassInformationType value) {
        return new JAXBElement<ClassInformationType>(_ClassInformation_QNAME, ClassInformationType.class, null, value);
    }

}
