//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.15 at 01:36:40 PM CST 
//


package com.ibm.ws.jpa.diagnostics.tools.appscanner.report.pascanresult.v10;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PersistenceParseResultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersistenceParseResultType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="originalHash" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="scannedHash" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="persistenceUnitDocument" type="{PersistentArchiveScanResult_1.0}PersistenceUnitType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[0-9]+(\.[0-9]+)*"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersistenceParseResultType", propOrder = {
    "originalHash",
    "scannedHash",
    "persistenceUnitDocument"
})
public class PersistenceParseResultType {

    @XmlElement(required = true)
    protected String originalHash;
    @XmlElement(required = true)
    protected String scannedHash;
    protected List<PersistenceUnitType> persistenceUnitDocument;
    @XmlAttribute(name = "version")
    protected String version;

    /**
     * Gets the value of the originalHash property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalHash() {
        return originalHash;
    }

    /**
     * Sets the value of the originalHash property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalHash(String value) {
        this.originalHash = value;
    }

    /**
     * Gets the value of the scannedHash property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScannedHash() {
        return scannedHash;
    }

    /**
     * Sets the value of the scannedHash property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScannedHash(String value) {
        this.scannedHash = value;
    }

    /**
     * Gets the value of the persistenceUnitDocument property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the persistenceUnitDocument property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPersistenceUnitDocument().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PersistenceUnitType }
     * 
     * 
     */
    public List<PersistenceUnitType> getPersistenceUnitDocument() {
        if (persistenceUnitDocument == null) {
            persistenceUnitDocument = new ArrayList<PersistenceUnitType>();
        }
        return this.persistenceUnitDocument;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
