//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.15 at 02:23:12 PM CST 
//


package com.ibm.ws.jpa.diagnostics.tools.appscanner.report.puscanresult.v10;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ibm.ws.jpa.diagnostics.tools.appscanner.report.puscanresult.v10 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PersistenceUnitScanResult_QNAME = new QName("PersistenceUnitScanResult_1.0", "PersistenceUnitScanResult");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ibm.ws.jpa.diagnostics.tools.appscanner.report.puscanresult.v10
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PersistenceUnitScanResultType }
     * 
     */
    public PersistenceUnitScanResultType createPersistenceUnitScanResultType() {
        return new PersistenceUnitScanResultType();
    }

    /**
     * Create an instance of {@link ClassScanResultType }
     * 
     */
    public ClassScanResultType createClassScanResultType() {
        return new ClassScanResultType();
    }

    /**
     * Create an instance of {@link ORMScanResultType }
     * 
     */
    public ORMScanResultType createORMScanResultType() {
        return new ORMScanResultType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersistenceUnitScanResultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "PersistenceUnitScanResult_1.0", name = "PersistenceUnitScanResult")
    public JAXBElement<PersistenceUnitScanResultType> createPersistenceUnitScanResult(PersistenceUnitScanResultType value) {
        return new JAXBElement<PersistenceUnitScanResultType>(_PersistenceUnitScanResult_QNAME, PersistenceUnitScanResultType.class, null, value);
    }

}
