//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.09 at 03:58:13 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "PersistentArchiveScanResult_1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ibm.ws.jpa.diagnostics.tools.appscanner.report.puscanresult.v10;
