//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.09 at 03:58:13 PM CST 
//


package com.ibm.ws.jpa.diagnostics.tools.appscanner.report.puscanresult.v10;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PersistentArchiveScanResultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersistentArchiveScanResultType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="persistenceUnitRootURL" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="persistenceUnitRootPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="relativePathLibraryJarPathMap" type="{PersistentArchiveScanResult_1.0}RelativePathLibraryJarPathMapType"/>
 *         &lt;element name="persistence" type="{PersistentArchiveScanResult_1.0}PersistenceParseResultType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement
@XmlType(name = "PersistentArchiveScanResultType", propOrder = {
    "persistenceUnitRootURL",
    "persistenceUnitRootPath",
    "relativePathLibraryJarPathMap",
    "persistence"
})
public class PersistentArchiveScanResultType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String persistenceUnitRootURL;
    @XmlElement(required = true)
    protected String persistenceUnitRootPath;
    @XmlElement(required = true)
    protected RelativePathLibraryJarPathMapType relativePathLibraryJarPathMap;
    @XmlElement(required = true)
    protected PersistenceParseResultType persistence;

    /**
     * Gets the value of the persistenceUnitRootURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersistenceUnitRootURL() {
        return persistenceUnitRootURL;
    }

    /**
     * Sets the value of the persistenceUnitRootURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersistenceUnitRootURL(String value) {
        this.persistenceUnitRootURL = value;
    }

    /**
     * Gets the value of the persistenceUnitRootPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersistenceUnitRootPath() {
        return persistenceUnitRootPath;
    }

    /**
     * Sets the value of the persistenceUnitRootPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersistenceUnitRootPath(String value) {
        this.persistenceUnitRootPath = value;
    }

    /**
     * Gets the value of the relativePathLibraryJarPathMap property.
     * 
     * @return
     *     possible object is
     *     {@link RelativePathLibraryJarPathMapType }
     *     
     */
    public RelativePathLibraryJarPathMapType getRelativePathLibraryJarPathMap() {
        return relativePathLibraryJarPathMap;
    }

    /**
     * Sets the value of the relativePathLibraryJarPathMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelativePathLibraryJarPathMapType }
     *     
     */
    public void setRelativePathLibraryJarPathMap(RelativePathLibraryJarPathMapType value) {
        this.relativePathLibraryJarPathMap = value;
    }

    /**
     * Gets the value of the persistence property.
     * 
     * @return
     *     possible object is
     *     {@link PersistenceParseResultType }
     *     
     */
    public PersistenceParseResultType getPersistence() {
        return persistence;
    }

    /**
     * Sets the value of the persistence property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersistenceParseResultType }
     *     
     */
    public void setPersistence(PersistenceParseResultType value) {
        this.persistence = value;
    }

}
