//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.15 at 02:23:12 PM CST 
//


package com.ibm.ws.jpa.diagnostics.tools.appscanner.report.puscanresult.v10;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PersistenceUnitScanResultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersistenceUnitScanResultType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="classScanResult" type="{PersistenceUnitScanResult_1.0}ClassScanResultType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ormScanResult" type="{PersistenceUnitScanResult_1.0}ORMScanResultType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement
@XmlType(name = "PersistenceUnitScanResultType", propOrder = {
    "name",
    "classScanResult",
    "ormScanResult"
})
public class PersistenceUnitScanResultType {

    @XmlElement(required = true)
    protected String name;
    protected List<ClassScanResultType> classScanResult;
    protected List<ORMScanResultType> ormScanResult;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the classScanResult property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the classScanResult property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClassScanResult().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClassScanResultType }
     * 
     * 
     */
    public List<ClassScanResultType> getClassScanResult() {
        if (classScanResult == null) {
            classScanResult = new ArrayList<ClassScanResultType>();
        }
        return this.classScanResult;
    }

    /**
     * Gets the value of the ormScanResult property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ormScanResult property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrmScanResult().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ORMScanResultType }
     * 
     * 
     */
    public List<ORMScanResultType> getOrmScanResult() {
        if (ormScanResult == null) {
            ormScanResult = new ArrayList<ORMScanResultType>();
        }
        return this.ormScanResult;
    }

}
